name: attend_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  provider: ^6.1.4
  cloud_firestore: ^4.14.0
  firebase_core: ^2.25.4
  url_launcher: ^6.1.10
  font_awesome_flutter: ^10.5.0
  intl: ^0.18.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/rise_logo.png