// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQMqJyxxIwGcGl6PYG1b00Qdv3xjThBH0',
    appId: '1:52505143413:web:b2fcf2c5948e5764b0303c',
    messagingSenderId: '52505143413',
    projectId: 'attend-app-6689b',
    authDomain: 'attend-app-6689b.firebaseapp.com',
    storageBucket: 'attend-app-6689b.firebasestorage.app',
    measurementId: 'G-TX96LF0R6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA78_TZ0uPaRfzwbGs-TWRSrnDxfXuKRYw',
    appId: '1:52505143413:android:706c07c56a9e6ed8b0303c',
    messagingSenderId: '52505143413',
    projectId: 'attend-app-6689b',
    storageBucket: 'attend-app-6689b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEiklrSqdPDpv7wHz7sWXnQMwLID-slAc',
    appId: '1:52505143413:ios:ac4a86d53ec87e9bb0303c',
    messagingSenderId: '52505143413',
    projectId: 'attend-app-6689b',
    storageBucket: 'attend-app-6689b.firebasestorage.app',
    iosBundleId: 'com.example.attendApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEiklrSqdPDpv7wHz7sWXnQMwLID-slAc',
    appId: '1:52505143413:ios:ac4a86d53ec87e9bb0303c',
    messagingSenderId: '52505143413',
    projectId: 'attend-app-6689b',
    storageBucket: 'attend-app-6689b.firebasestorage.app',
    iosBundleId: 'com.example.attendApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQMqJyxxIwGcGl6PYG1b00Qdv3xjThBH0',
    appId: '1:52505143413:web:ec1c6c2c44adf733b0303c',
    messagingSenderId: '52505143413',
    projectId: 'attend-app-6689b',
    authDomain: 'attend-app-6689b.firebaseapp.com',
    storageBucket: 'attend-app-6689b.firebasestorage.app',
    measurementId: 'G-CPW0THVJHL',
  );
}
